spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            # 调度器实例名称
            instanceName: clusteredScheduler
            # 调度器实例编号自动生成
            instanceId: AUTO
          jobStore:
            # 持久化方式配置
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            # 持久化方式配置数据驱动，MySQL数据库
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # quartz相关数据表前缀名
            tablePrefix: QRTZ_
            # 开启分布式配置
            isClustered: true
            # 分布式节点有效性检查时间间隔，单位：毫秒
            clusterCheckinInterval: 20000
            useProperties: false
          threadPool:
            # 线程池实现类
            class: org.quartz.simpl.SimpleThreadPool
            # 执行最大鬓发线程数量
            threadCount: 10
            # 线程优先级
            threadPriority: 5
            # 配置是否启动自动加载数据库内的定时任务，默认true
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.119:3306/quartzdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: quartz-cluster-node-first
server:
  port: 8081
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
